name: Lint and Format Check

on: push

jobs:
  main:
    name: Run ESLint and Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up pNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install ESLint and Prettier
        run: pnpm install

      - name: Run ESLint
        run: npm run lint:check

      - name: Run Prettier
        run: npm run format:check
