name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE.txt'
      - '**/.replit'
      - '**/replit.nix'

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install terser
        run: npm install -g terser
      - name: Install CSSO
        run: npm install -g csso-cli
      - name: Install HTMLMinifier
        run: npm install -g html-minifier

      - name: Minify JS
        run: for i in *.js; do terser $i --compress -o $i; done
      - name: Minify CSS
        run: for i in *.css; do csso $i -o $i; done
      - name: Minify HTML
        run: for i in *.html; do html-minifier $i -o $i; done

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TYLERGORDONHILL_C8339 }}'
          projectId: tylergordonhill-c8339
          channelId: live
