name: Deploy 
on:
  push:
    branches:
      - main
concurrency:
  group: "deploy"
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TYLERGORDONHILL_C8339 }}'
          projectId: tylergordonhill-c8339
          channelId: live
